blueprint:
  name: Duotecno_Lights_on_off_dubbele richting_lights_dim_enkele_richting
  domain: automation
  author: Duotecno
  input:
    light_1:
      name: Master
      selector:
        entity:
          domain: light

    light_2:
      name: Slave
      selector:
        entity:
          domain: light

trigger:
  - entity_id:
      - !input light_1
      - !input light_2
    platform: state
  - entity_id:
      - !input light_1
    platform: state
    attribute: brightness
action:
  - entity_id:
      - !input light_1
      - !input light_2
    service: '{% if trigger.to_state.state == "on" %} light.turn_on
      {% elif trigger.to_state.state == "off" %} light.turn_off
      {% endif %}'
  - entity_id:
      - !input light_2
    condition: state
    state: "on"
  - service: light.turn_on
    data:
      brightness: "{{ trigger.to_state.attributes.brightness }}"
    entity_id:
      - !input light_2
