blueprint:
  name: Duotecno_lights_on_off_dim_dubbele_richting
  description: Bind 2 light entities together to act in unison
  domain: automation
  input:
    light_1:
      name: Light 1
      selector:
        entity:
          domain: light

    light_2:
      name: Light 2
      selector:
        entity:
          domain: light

trigger:
  - entity_id:
      - !input light_1
      - !input light_2
    platform: state
  - entity_id:
      - !input light_1
      - !input light_2
    platform: state
    attribute: brightness
action:
  - entity_id:
      - !input light_1
      - !input light_2
    service: '{% if trigger.to_state.state == "on" %} light.turn_on {% elif trigger.to_state.state == "off" %} light.turn_off {% endif %}'
  - entity_id:
      - !input light_1
      - !input light_2
    condition: state
    state: "on"
  - service: light.turn_on
    data:
      brightness: "{{ trigger.to_state.attributes.brightness }}"
    entity_id:
      - !input light_1
      - !input light_2
